[build-system]
requires = []
build-backend = "setuptools.build_meta"
backend-path = ["."]

[tool.black]
skip-string-normalization = true

[tool.setuptools_scm]

[tool.pytest-enabler.black]
#addopts = "--black"

[tool.pytest-enabler.mypy]
#addopts = "--mypy"

[tool.pytest-enabler.cov]
addopts = "--cov"

[tool.pytest-enabler.ruff]
addopts = "--ruff"

[tool.pytest-enabler.xdist]
addopts = "-n auto"
